// GENERATED CODE - DO NOT MODIFY BY HAND
// This file was generated by Hive adapter generator

part of 'wallet.dart';

class WalletAdapter extends TypeAdapter<Wallet> {
  @override
  final typeId = 2;

  @override
  Wallet read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Wallet(
      id: fields[0] as String,
      name: fields[1] as String,
      type: fields[2] as String,
      initialBalance: fields[3] as double,
      icon: fields[4] as String,
      colorValue: fields[5] as int,
      isDefault: fields[6] as bool? ?? false,
      createdAt: fields[7] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, Wallet obj) {
    writer
      ..writeByte(8)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.name)
      ..writeByte(2)
      ..write(obj.type)
      ..writeByte(3)
      ..write(obj.initialBalance)
      ..writeByte(4)
      ..write(obj.icon)
      ..writeByte(5)
      ..write(obj.colorValue)
      ..writeByte(6)
      ..write(obj.isDefault)
      ..writeByte(7)
      ..write(obj.createdAt);
  }
}
